name: CI
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Xvfb
        run: sudo apt-get install -y xvfb

      - name: Start Xvfb
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          export DISPLAY=:99

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          EBAY_EMAIL: ${{ secrets.EBAY_EMAIL }}
          EBAY_PASS: ${{ secrets.EBAY_PASS }}
        run: pytest tests/ --alluredir=allure-results

      - name: Generate Allure report
        if: always()
        uses: simple-elf/allure-report-action@v1.5
        with:
          allure_results_dir: allure-results
          allure_report_dir: allure-report

      - name: Deploy Allure report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report